### ISSUE TITLE
[ Feat ] 햄버거 메뉴바 추가

### ISSUE THREAD

**Issue by pepperdad** [TEAM-BEAT/BEAT-Client#110]
### 🛠 Issue

<img width="622" alt="image" src="https://github.com/user-attachments/assets/5d6018b9-f933-40c4-963c-c406721977ad">

### 📝 To-do

- [ ] 햄버거 메뉴바 추가

### 🔍 접근 방법

로그인 여부에 따라서 보이는 뷰 다르게 설정

**Comment by sinji2102** [comment]
햄버거 메뉴바 제가 스틸하겟습니다 ㅋㅋ
