### ISSUE TITLE
[ Feat ] chromatic으로 스토리북 배포

### ISSUE THREAD

**Issue by imddoy** [TEAM-BEAT/BEAT-Client#27]
### 🛠 Issue

시각적 회귀 테스트를 위한 chromatic으로 스토리북 배포하기
(pull을 받아서 개발 서버를 실행하고 어떤 UI인지 확인하고 제대로 작동하는지 손수 테스트를 진행하지 않아도 됨~!!)

### 📝 To-do

- [ ] chromatic 설치
- [ ] 지속적 배포

### 🔍 접근 방법

튜토리얼 보면서 따라해볼게요~

**Comment by pepperdad** [comment]
최고채현~!
