### ISSUE TITLE
[ Feat ] PWA 설정

### ISSUE THREAD

**Issue by imddoy** [TEAM-BEAT/BEAT-Client#299]
### 🛠 Issue

PWA A2HS 설정

### 📝 To-do

- [ ] 아이콘 png로 변경(svg는 애플에서 안되나봄...)
- [ ] themecolor(주소 표시줄, 상태 표시줄 등) 변경(아무생각없이 pink로 디자인 선생님들한테 혼남...헤헤)

### 🔍 접근 방법

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable
https://shallwestudy.tistory.com/19
https://fe-developers.kakaoent.com/2023/230202-a2hs/

**Comment by pepperdad** [comment]
ㄷㄷ 쉬라고 ㅋㅋ
