### ISSUE TITLE
[ Refactor ] 등록하기 디자인 1차 스프린트 반영

### ISSUE THREAD

**Issue by imddoy** [TEAM-BEAT/BEAT-Client#356]
### ♻️ Issue

등록하기에서 글자 수를 조금 늘려요
포스터 비율 바꿔요

### 🔢 리팩토링하는 이슈를 기입해주세요.

#351

### 📣 리팩토링 목적

1. 공연 제목이 10자는 너무 짧아요
2. 소개글 300자로 원래대로 하려고 하는데 그냥 500자로 확 늘리기로 결정했어요

### 📝 To-do

그냥 max만 바꿔요
height바꿔요

**Comment by sinji2102** [comment]
@imddoy #357 PR 닫힌 거로 알고 있어 Issue close 하겠습니다!!
