### ISSUE TITLE
[ Feat ] 스태프리스트, 캐스트리스트 수정 가능하도록 구현

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#361]
### 🛠 Issue

잠시 막아두었던 STEP2 ( 스태프리스트, 캐스트리스트 수정 스텝)을 다시 살리고,
바뀐 API 명세에 따라 수정 로직을 조정하도록 하겠습니다.

### 📝 To-do

- [x] STEP 2 부활
- [ ] 바뀐 API 명세에 맞게 공연 수정하기 로직 변경

### 🔍 접근 방법

바뀐 API 명세에 따라 ScheduleList, CastList, StaffList 를 수정, 추가, 삭제하는 로직 구현

**Comment by sinji2102** [comment]
merge 된 거로 확인해서 close 하겠습니다!
