### ISSUE TITLE
[ Feat ] Navigation 공통 컴포넌트 추가

### ISSUE THREAD

**Issue by pepperdad** [TEAM-BEAT/BEAT-Client#44]
### 🛠 Issue

<img width="798" alt="image" src="https://github.com/TEAM-BEAT/BEAT-Client/assets/58854041/481b7bb9-b045-48a2-aa7e-78ba9c9ecd5a">

### 📝 To-do

- [x] Navigation 구현

### 🔍 접근 방법

.

**Comment by imddoy** [comment]
ㄷㄷ 폭주하는 리드 너무 든든하다
