### ISSUE TITLE
[ Feat ] Stepper 공통 컴포넌트 추가

### ISSUE THREAD

**Issue by imddoy** [TEAM-BEAT/BEAT-Client#53]
### 🛠 Issue

<img width="664" alt="image" src="https://github.com/TEAM-BEAT/BEAT-Client/assets/90364711/62388dd2-2444-419b-8714-29d11fa5ec8c">
헤헤 이쁘죠?
이걸 만드려구요~

### 📝 To-do

- [x] 쌈@뽕하게 만들기

### 🔍 접근 방법

이쁜만큼 내 코드도 이뿌게.....

**Comment by pepperdad** [comment]
이쁩니다 그러니까 얼른 만드시죠?
