### ISSUE TITLE
[ Fix ] 컨벤션에 맞게 공통 컴포넌트 리네이밍

### ISSUE THREAD

**Issue by ocahs9** [TEAM-BEAT/BEAT-Client#54]
### 🛠 Issue

컨벤션에 맞게 공통 컴포넌트 리네이밍

### 📝 To-do

공통 컴포넌트 이름 리네이밍
textAreas나 textFields 리네이밍 

### 🔍 접근 방법

.

**Comment by pepperdad** [comment]
최고다 공준혁
